### ISSUE TITLE
Fix scrutinizer tests

### ISSUE THREAD

**Issue by galileo** [galileo/GalileoSettingBundle#8]
After changing dependencies we the test on scrutinizer are not passing anymore

~~~
bin/phpspec run -f progress -c phpspec-ci.yml
~~~

> PHP Fatal error:  Uncaught Error: Class name must be a valid object or a string in /home/scrutinizer/build/vendor/phpspec/phpspec/src/PhpSpec/Console/Application.php:153
Stack trace:
#0 /home/scrutinizer/build/vendor/phpspec/phpspec/src/PhpSpec/Console/Application.php(81): PhpSpec\Console\Application->loadConfigurationFile(Object(Symfony\Component\Console\Input\ArgvInput), Object(PhpSpec\ServiceContainer))
#1 /home/scrutinizer/build/vendor/symfony/console/Application.php(123): PhpSpec\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /home/scrutinizer/build/vendor/phpspec/phpspec/bin/phpspec(26): Symfony\Component\Console\Application->run()
#3 {main}
  thrown in /home/scrutinizer/build/vendor/phpspec/phpspec/src/PhpSpec/Console/Application.php on line 153

**Comment by galileo** [comment]
Done with new release 1.0.3
